In [1]:
import numpy as np

In [2]:
arr_1s = np.array([[1,1,1],
                 [1,1,1],
                 [1,1,1]])
print(arr_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
arra_1s = np.ones(3)
print(arra_1s)

[1. 1. 1.]


In [5]:
array_1s = np.ones((3,3)) #same work as the above matrix did 
print(array_1s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
array_1s.dtype #it outputs in float

dtype('float64')

In [15]:
arr1s = np.ones((3,3), dtype = int)
print(arr1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
arr0s = np.zeros((4,4), dtype=int)
print(arr0s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [19]:
arr_empty = np.empty((3,3))
print(arr_empty)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
